In [0]:
%pip install faker

Collecting faker
  Downloading faker-40.28.1-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.28.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 44.9 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.28.1
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
dbutils.library.restartPython()

In [0]:
import pandas as pd
import random
from faker import Faker
from datetime import datetime, timedelta

In [0]:
fake = Faker("en_IN")

# Makes dataset reproducible
random.seed(42)
Faker.seed(42)

In [0]:
cities = {
    "Delhi": "Delhi",
    "Mumbai": "Maharashtra",
    "Pune": "Maharashtra",
    "Jaipur": "Rajasthan",
    "Lucknow": "Uttar Pradesh",
    "Hyderabad": "Telangana",
    "Bangalore": "Karnataka",
    "Chennai": "Tamil Nadu",
    "Ahmedabad": "Gujarat",
    "Kolkata": "West Bengal",
    "Indore": "Madhya Pradesh",
    "Bhopal": "Madhya Pradesh",
    "Surat": "Gujarat",
    "Patna": "Bihar",
    "Noida": "Uttar Pradesh"
}

membership_levels = [
    "Silver",
    "Gold",
    "Platinum"
]

customer_status = [
    "Active",
    "Inactive"
]

In [0]:
customers = []

for customer_id in range(1001, 1501):

    city = random.choice(list(cities.keys()))

    customer = {
        "customer_id": customer_id,
        "customer_name": fake.name(),
        "gender": random.choice(["Male", "Female"]),
        "city": city,
        "state": cities[city],
        "email": fake.email(),
        "phone": str(random.randint(6000000000, 9999999999)),
        "membership": random.choice(membership_levels),
        "annual_spend": random.randint(5000, 150000),
        "last_purchase_date": fake.date_between(
            start_date="-2y",
            end_date="today"
        ),
        "status": random.choice(customer_status)
    }

    customers.append(customer)

In [0]:
master_df = pd.DataFrame(customers)

print("Number of Customers:", len(master_df))

master_df.head()

Number of Customers: 500

   customer_id        customer_name  ... last_purchase_date    status
0         1001        Aryan Maharaj  ...         2024-09-17  Inactive
1         1002          Pahal Balay  ...         2025-07-09    Active
2         1003         Rushil Saini  ...         2026-01-10    Active
3         1004            Pahal Oak  ...         2024-09-10  Inactive
4         1005  Jagrati Padmanabhan  ...         2026-06-16    Active

[5 rows x 11 columns]

In [0]:
# -----------------------------
# Introduce Dirty Data
# -----------------------------

# 1. Add 20 duplicate records
duplicate_rows = master_df.sample(n=20, random_state=42)

master_df = pd.concat([master_df, duplicate_rows], ignore_index=True)

# 2. Make 10 customer names NULL
name_null_index = random.sample(list(master_df.index), 10)
master_df.loc[name_null_index, "customer_name"] = None

# 3. Make 10 annual_spend values NULL
spend_null_index = random.sample(list(master_df.index), 10)
master_df.loc[spend_null_index, "annual_spend"] = None

# 4. Make 10 invalid emails
email_invalid_index = random.sample(list(master_df.index), 10)
master_df.loc[email_invalid_index, "email"] = "invalid_email"

print("Dirty data created successfully!")
print("Total Records :", len(master_df))

Dirty data created successfully!
Total Records : 520

In [0]:
print("Duplicate Rows Added :", len(master_df) - 500)

print("\nMissing Customer Names :", master_df["customer_name"].isnull().sum())

print("Missing Annual Spend :", master_df["annual_spend"].isnull().sum())

print("Invalid Emails :",
      (master_df["email"] == "invalid_email").sum())

Duplicate Rows Added : 20

Missing Customer Names : 10
Missing Annual Spend : 10
Invalid Emails : 10

In [0]:
master_df.head(10)

   customer_id        customer_name  ... last_purchase_date    status
0         1001        Aryan Maharaj  ...         2024-09-17  Inactive
1         1002          Pahal Balay  ...         2025-07-09    Active
2         1003         Rushil Saini  ...         2026-01-10    Active
3         1004            Pahal Oak  ...         2024-09-10  Inactive
4         1005  Jagrati Padmanabhan  ...         2026-06-16    Active
5         1006         Farhan Memon  ...         2024-12-18    Active
6         1007           Fariq Kaul  ...         2025-10-12  Inactive
7         1008   Nicholas Prabhakar  ...         2025-10-12  Inactive
8         1009          Nihal Shere  ...         2025-08-16    Active
9         1010         Daksh Karnik  ...         2024-08-22    Active

[10 rows x 11 columns]

In [0]:
import os

print(os.getcwd())

/Workspace/Users/kushagrastudy.9@gmail.com

In [0]:
display(dbutils.fs.ls("/"))

path,name,size,modificationTime
dbfs:/Volumes/,Volumes/,0,0
dbfs:/Workspace/,Workspace/,0,0
dbfs:/databricks-datasets/,databricks-datasets/,0,0

In [0]:
# Convert Pandas DataFrame to Spark DataFrame
master_spark_df = spark.createDataFrame(master_df)

print("Spark DataFrame created successfully!")
display(master_spark_df.limit(10))

Spark DataFrame created successfully!

customer_id,customer_name,gender,city,state,email,phone,membership,annual_spend,last_purchase_date,status
1001,Aryan Maharaj,Male,Ahmedabad,Gujarat,udantdewan@example.net,9961228449,Gold,25656.0,2024-09-17,Inactive
1002,Pahal Balay,Female,Patna,Bihar,chandertejas@example.org,8479708607,Silver,23233.0,2025-07-09,Active
1003,Rushil Saini,Male,Indore,Madhya Pradesh,saumyamall@example.org,9320303242,Gold,25916.0,2026-01-10,Active
1004,Pahal Oak,Male,Patna,Bihar,nachiket35@example.org,7632629719,Gold,123858.0,2024-09-10,Inactive
1005,Jagrati Padmanabhan,Female,Pune,Maharashtra,caleb78@example.org,7525876051,Silver,74986.0,2026-06-16,Active
1006,Farhan Memon,Male,Kolkata,West Bengal,rehaan10@example.net,8294113287,Platinum,69175.0,2024-12-18,Active
1007,Fariq Kaul,Female,Chennai,Tamil Nadu,raiarunima@example.com,7159417075,Platinum,62570.0,2025-10-12,Inactive
1008,Nicholas Prabhakar,Male,Patna,Bihar,shaurya41@example.net,6983753977,Silver,87694.0,2025-10-12,Inactive
1009,Nihal Shere,Male,Lucknow,Uttar Pradesh,omadan@example.net,6906164396,Platinum,87490.0,2025-08-16,Active
1010,Daksh Karnik,Female,Indore,Madhya Pradesh,muttinandini@example.com,7699226064,Platinum,null,2024-08-22,Active

In [0]:
print("Total Records:", master_spark_df.count())

Total Records: 520

In [0]:
from pyspark.sql import SparkSession

print("Spark Version:", spark.version)

print("\nCurrent Catalog:")
try:
    print(spark.sql("SELECT current_catalog()").collect()[0][0])
except Exception as e:
    print("Not available:", e)

print("\nCurrent Schema:")
try:
    print(spark.sql("SELECT current_schema()").collect()[0][0])
except Exception as e:
    print("Not available:", e)

print("\nCurrent Working Directory:")
try:
    import os
    print(os.getcwd())
except Exception as e:
    print(e)

Spark Version: 4.1.0

Current Catalog:
workspace

Current Schema:
default

Current Working Directory:
/Workspace/Users/kushagrastudy.9@gmail.com

In [0]:
import random
from pyspark.sql import Row

random.seed(42)

first_names = [
    "Aarav","Vivaan","Aditya","Krishna","Arjun","Rohan","Rahul",
    "Priya","Ananya","Sneha","Neha","Pooja","Kavya","Diya"
]

last_names = [
    "Sharma","Verma","Patel","Gupta","Singh",
    "Mehta","Jain","Joshi","Kapoor","Agarwal"
]

cities = [
    "Delhi","Mumbai","Pune","Jaipur",
    "Ahmedabad","Bengaluru","Chennai","Hyderabad"
]

records = []

for i in range(1, 501):

    first = random.choice(first_names)
    last = random.choice(last_names)

    email = f"{first.lower()}.{last.lower()}{i}@gmail.com"

    # Introduce invalid emails
    if random.random() < 0.05:
        email = "invalid_email"

    # Introduce null emails
    if random.random() < 0.05:
        email = None

    phone = "9" + "".join(str(random.randint(0,9)) for _ in range(9))

    # Introduce null phone numbers
    if random.random() < 0.05:
        phone = None

    city = random.choice(cities)

    records.append(
        Row(
            customer_id=i,
            first_name=first,
            last_name=last,
            email=email,
            phone=phone,
            city=city
        )
    )

# Add duplicate rows intentionally
records.extend(records[:20])

master_df = spark.createDataFrame(records)

print("Total Rows:", master_df.count())

display(master_df.limit(10))

Total Rows: 520

customer_id,first_name,last_name,email,phone,city
1,Neha,Verma,invalid_email,9321819600,Jaipur
2,Ananya,Agarwal,invalid_email,9863794026,Pune
3,Krishna,Mehta,krishna.mehta3@gmail.com,9559407816,Ahmedabad
4,Diya,Agarwal,diya.agarwal4@gmail.com,9310341316,Bengaluru
5,Aditya,Mehta,aditya.mehta5@gmail.com,9192832764,Jaipur
6,Neha,Mehta,neha.mehta6@gmail.com,9305641395,Hyderabad
7,Rahul,Joshi,rahul.joshi7@gmail.com,9884969653,Pune
8,Ananya,Joshi,null,9122691669,Ahmedabad
9,Ananya,Sharma,ananya.sharma9@gmail.com,9845146270,Ahmedabad
10,Ananya,Patel,ananya.patel10@gmail.com,9489325288,Bengaluru

In [0]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nTrying to create a test folder...")

test_path = "/Workspace/Users/kushagrastudy.9@gmail.com/delta_assignment_test"

try:
    os.makedirs(test_path, exist_ok=True)
    
    with open(f"{test_path}/test.txt", "w") as f:
        f.write("Databricks write test")

    print("SUCCESS")
    print("Created:", test_path)
    print("Files:", os.listdir(test_path))

except Exception as e:
    print("FAILED")
    print(type(e).__name__)
    print(e)

Current working directory:
/Workspace/Users/kushagrastudy.9@gmail.com

Trying to create a test folder...
SUCCESS
Created: /Workspace/Users/kushagrastudy.9@gmail.com/delta_assignment_test
Files: ['test.txt']

In [0]:
import os
import shutil

output_dir = "/Workspace/Users/kushagrastudy.9@gmail.com/delta_assignment"

os.makedirs(output_dir, exist_ok=True)

temp_dir = f"{output_dir}/customer_master_temp"

# Remove old temp directory if it exists
if os.path.exists(temp_dir):
    shutil.rmtree(temp_dir)

# Write as a single CSV
(master_df
    .coalesce(1)
    .write
    .mode("overwrite")
    .option("header", True)
    .csv(temp_dir)
)

# Find the generated CSV file
csv_file = [f for f in os.listdir(temp_dir) if f.startswith("part-") and f.endswith(".csv")][0]

# Rename it to customer_master.csv
shutil.copy(
    os.path.join(temp_dir, csv_file),
    os.path.join(output_dir, "customer_master.csv")
)

print("Master dataset exported successfully!")
print("Location:", os.path.join(output_dir, "customer_master.csv"))

---------------------------------------------------------------------------
SparkException                            Traceback (most recent call last)
File <command-5783324624416543>, line 20
     12     shutil.rmtree(temp_dir)
     14 # Write as a single CSV
     15 (master_df
     16     .coalesce(1)
     17     .write
     18     .mode("overwrite")
     19     .option("header", True)
---> 20     .csv(temp_dir)
     21 )
     23 # Find the generated CSV file
     24 csv_file = [f for f in os.listdir(temp_dir) if f.startswith("part-") and f.endswith(".csv")][0]

File /databricks/python/lib/python3.12/site-packages/pyspark/sql/connect/readwriter.py:831, in DataFrameWriter.csv(self, path, mode, compression, sep, quote, escape, header, nullValue, escapeQuotes, quoteAll, dateFormat, timestampFormat, ignoreLeadingWhiteSpace, ignoreTrailingWhiteSpace, charToEscapeQuoteEscaping, encoding, emptyValue, lineSep)
    812 self.mode(mode)
    813 self._set_opts(
    814     compression=compression,
    815     sep=sep,
   (...)
    829     lineSep=lineSep,
    830 )
--> 831 self.format("csv").save(path)

File /databricks/python/lib/python3.12/site-packages/pyspark/sql/connect/readwriter.py:703, in DataFrameWriter.save(self, path, format, mode, partitionBy, **options)
    701     self.format(format)
    702 self._write.path = path
--> 703 _, _, ei = self._spark.client.execute_command(
    704     self._write.command(self._spark.client), self._write.observations
    705 )
    706 self._callback(ei)

File /databricks/python/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py:1538, in SparkConnectClient.execute_command(self, command, observations, extra_request_metadata)
   1536     req.user_context.user_id = self._user_id
   1537 self._set_command_in_plan(req.plan, command)
-> 1538 data, _, metrics, observed_metrics, properties = self._execute_and_fetch(
   1539     req, observations or {}, extra_request_metadata
   1540 )
   1541 # Create a query execution object.
   1542 ei = ExecutionInfo(metrics, observed_metrics)

File /databricks/python/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py:2086, in SparkConnectClient._execute_and_fetch(self, req, observations, extra_request_metadata, self_destruct)
   2083 properties: Dict[str, Any] = {}
   2085 with Progress(handlers=self._progress_handlers, operation_id=req.operation_id) as progress:
-> 2086     for response in self._execute_and_fetch_as_iterator(
   2087         req, observations, extra_request_metadata or [], progress=progress
   2088     ):
   2089         if isinstance(response, StructType):
   2090             schema = response

File /databricks/python/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py:2062, in SparkConnectClient._execute_and_fetch_as_iterator(self, req, observations, extra_request_metadata, progress)
   2060     raise kb
   2061 except Exception as error:
-> 2062     self._handle_error(error)

File /databricks/python/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py:2380, in SparkConnectClient._handle_error(self, error)
   2378     self.thread_local.inside_error_handling = True
   2379     if isinstance(error, grpc.RpcError):
-> 2380         self._handle_rpc_error(error)
   2381     raise error
   2382 finally:

File /databricks/python/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py:2458, in SparkConnectClient._handle_rpc_error(self, rpc_error)
   2454             logger.debug(f"Received ErrorInfo: {info}")
   2456             self._handle_rpc_error_with_error_info(info, status.message, status_code)  # EDGE
-> 2458             raise convert_exception(
   2459                 info,
   2460                 status.message,
   2461                 self._fetch_enriched_error(info),
   2462                 self._display_server_stack_trace(),
   2463                 status_code,
   2464             ) from None
   2466     raise SparkConnectGrpcException(
   2467         message=status.message,
   2468         sql_state=ErrorCode.CLIENT_UNEXPECTED_MISSING_SQL_STATE,  # EDGE
   2469         grpc_status_code=status_code,
   2470     ) from None
   2471 else:

SparkException: Job aborted due to stage failure: java.io.IOException: Mkdirs failed to create /Workspace/Users/kushagrastudy.9@gmail.com/delta_assignment/customer_master_temp (exists=false, cwd=file:/databricks/spark/work/app-20260627111541-0000/0)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:774)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:759)
	at com.databricks.backend.daemon.driver.SharedUCWorkspaceLocalFileSystem.$anonfun$create$3(SharedUCWorkspaceLocalFileSystem.scala:265)
	at com.databricks.backend.daemon.driver.SharedUCWorkspaceLocalFileSystem.$anonfun$create$3$adapted(SharedUCWorkspaceLocalFileSystem.scala:256)
	at com.databricks.backend.daemon.driver.WSFSCredentialForwardingHelper.$anonfun$withWSFSCredentials$1(WorkspaceLocalFileSystem.scala:254)
	at com.databricks.backend.daemon.driver.WSFSCredentialForwardingHelper.withWSFSCredentials(WorkspaceLocalFileSystem.scala:225)
	at com.databricks.backend.daemon.driver.WSFSCredentialForwardingHelper.withWSFSCredentials(WorkspaceLocalFileSystem.scala:254)
	at com.databricks.backend.daemon.driver.WSFSCredentialForwardingHelper.withWSFSCredentials$(WorkspaceLocalFileSystem.scala:252)
	at com.databricks.backend.daemon.driver.SharedUCWorkspaceLocalFileSystem.withWSFSCredentials(SharedUCWorkspaceLocalFileSystem.scala:33)
	at com.databricks.backend.daemon.driver.SharedUCWorkspaceLocalFileSystem.$anonfun$create$2(SharedUCWorkspaceLocalFileSystem.scala:256)
	at com.databricks.backend.daemon.driver.SharedUCWorkspaceLocalFileSystem.withBlockOperationOnWSFSRootDir(SharedUCWorkspaceLocalFileSystem.scala:138)
	at com.databricks.backend.daemon.driver.SharedUCWorkspaceLocalFileSystem.$anonfun$create$1(SharedUCWorkspaceLocalFileSystem.scala:256)
	at com.databricks.backend.daemon.driver.SharedUCWorkspaceLocalFileSystem.withSharedUcPathEnforcement(SharedUCWorkspaceLocalFileSystem.scala:81)
	at com.databricks.backend.daemon.driver.SharedUCWorkspaceLocalFileSystem.create(SharedUCWorkspaceLocalFileSystem.scala:254)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$create$4(DatabricksFileSystemV2.scala:1058)
	at com.databricks.s3a.S3AExceptionUtils$.convertAWSExceptionToJavaIOException(DatabricksStreamUtils.scala:65)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$create$3(DatabricksFileSystemV2.scala:1055)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$withUserContextRecorded$2(DatabricksFileSystemV2.scala:1510)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:850)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:850)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withUserContextRecorded(DatabricksFileSystemV2.scala:1483)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$create$2(DatabricksFileSystemV2.scala:1054)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:531)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:669)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$6(UsageLogging.scala:696)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:850)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:850)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$5(UsageLogging.scala:664)
	at com.databricks.logging.UsageLogging.withOtelSpanInContext$1(UsageLogging.scala:656)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:659)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:540)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperationWithResultTags(DatabricksFileSystemV2.scala:850)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:532)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:496)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperation(DatabricksFileSystemV2.scala:850)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.create(DatabricksFileSystemV2.scala:1051)
	at com.databricks.backend.daemon.data.client.DBFSV2.super$create(DatabricksFileSystemV2.scala:727)
	at com.databricks.backend.daemon.data.client.DBFSV2.$anonfun$create$1(DatabricksFileSystemV2.scala:727)
	at com.databricks.backend.daemon.data.client.DbfsExceptionMapperImpl.withExceptionWrapping(DbfsSparkException.scala:39)
	at com.databricks.backend.daemon.data.client.DBFSV2.create(DatabricksFileSystemV2.scala:727)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystem.create(DatabricksFileSystem.scala:139)
	at com.databricks.sql.io.LokiFileSystem.$anonfun$create$4(LokiFileSystem.scala:573)
	at com.databricks.sql.io.LokiFileSystem.tryWithNativeIO(LokiFileSystem.scala:622)
	at com.databricks.sql.io.LokiFileSystem.$anonfun$create$1(LokiFileSystem.scala:573)
	at com.databricks.sql.io.LokiFileSystem$.withWrappedExceptions(LokiFileSystem.scala:158)
	at com.databricks.sql.io.LokiFileSystem.create(LokiFileSystem.scala:574)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1233)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1210)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1091)
	at com.databricks.sql.transaction.directory.DirectoryAtomicCommitProtocol.newTaskTempFileAbsPath(DirectoryAtomicCommitProtocol.scala:137)
	at com.databricks.sql.transaction.directory.DirectoryAtomicCommitProtocol.newTaskTempFile(DirectoryAtomicCommitProtocol.scala:112)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.newOutputWriter(FileFormatDataWriter.scala:284)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.<init>(FileFormatDataWriter.scala:274)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:619)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1700)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:644)
	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:134)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:978)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:978)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:67)
	at org.apache.spark.rdd.RDD.$anonfun$computeOrReadCheckpoint$1(RDD.scala:444)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:441)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:408)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$6(ResultTask.scala:107)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:107)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:233)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:223)
	at org.apache.spark.scheduler.Task.$anonfun$run$6(Task.scala:179)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:128)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:133)
	at scala.util.Using$.resource(Using.scala:296)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:132)
	at org.apache.spark.scheduler.TaskExecutionUtils$.withUCHandleForTaskExecution(Task.scala:391)
	at org.apache.spark.scheduler.Task.$anonfun$run$3(Task.scala:173)
	at org.apache.spark.scheduler.TaskExecutionUtils$.withCredentialsForTaskExecution(Task.scala:368)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:114)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$15(Executor.scala:1613)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:86)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:83)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:118)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:1618)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:1429)
	at com.databricks.aether.RDDTask.run(RDDTask.scala:296)
	at com.databricks.aether.worker.WorkerTaskAttemptThread.$anonfun$runInternal$1(AetherWorkerImpl.scala:366)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.aether.AetherInt64Gauge.scopedAdd(AetherServiceMetricImpls.scala:129)
	at com.databricks.aether.worker.WorkerTaskAttemptThread.runInternal(AetherWorkerImpl.scala:355)
	at com.databricks.aether.worker.WorkerTaskAttemptThread.run(AetherWorkerImpl.scala:332)
	at com.databricks.aether.FairBlockingQueue$SlotCountingRunnable.run(FairBlockingQueue.java:647)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)


JVM stacktrace:
org.apache.spark.SparkException
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$failJobAndIndependentStages$1(DAGScheduler.scala:6028)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:6026)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$4(DAGScheduler.scala:5927)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$4$adapted(DAGScheduler.scala:5914)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$1(DAGScheduler.scala:5914)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:5903)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$4(DAGScheduler.scala:2357)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$4$adapted(DAGScheduler.scala:2344)
	at scala.Option.foreach(Option.scala:437)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:2344)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:2332)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:6499)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.liftedTree1$1(DAGScheduler.scala:6303)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:6294)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:6263)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:56)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$runJob$1(DAGScheduler.scala:1894)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:201)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1878)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:3457)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:3438)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeWrite$10(FileFormatWriter.scala:500)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.ignoreMaxResultLimit(FileFormatWriter.scala:942)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeWrite$9(FileFormatWriter.scala:498)
	at org.apache.spark.sql.catalyst.MetricKeyUtils$.measureMs(MetricKey.scala:2632)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeWrite$8(FileFormatWriter.scala:498)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.writeAndCommit(FileFormatWriter.scala:459)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeWrite(FileFormatWriter.scala:495)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$1(FileFormatWriter.scala:349)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)

In [0]:
import tempfile
import shutil

test_dir = f"/tmp/delta_test_{tempfile.gettempprefix()}"

try:
    (master_df
        .limit(5)
        .write
        .mode("overwrite")
        .option("header", True)
        .csv(test_dir)
    )

    print("SUCCESS")
    print("Spark can write to:", test_dir)

except Exception as e:
    print("FAILED")
    print(type(e).__name__)
    print(e)

FAILED
UnsupportedOperationException
[DBFS_DISABLED] Public DBFS root is disabled. Access is denied on path: /tmp/delta_test_tmp/_delta_log SQLSTATE: 56038

JVM stacktrace:
com.databricks.backend.daemon.data.client.DbfsUnsupportedOperationSparkException
	at com.databricks.backend.daemon.data.client.DbfsExceptionMapperImpl.withExceptionWrapping(DbfsSparkException.scala:42)
	at com.databricks.backend.daemon.data.client.DBFSV2.getFileStatus(DatabricksFileSystemV2.scala:752)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystem.getFileStatus(DatabricksFileSystem.scala:212)
	at com.databricks.sql.io.LokiFileSystem.$anonfun$getFileStatusNoCache$4(LokiFileSystem.scala:650)
	at com.databricks.sql.io.LokiFileSystem.tryWithNativeIO(LokiFileSystem.scala:622)
	at com.databricks.sql.io.LokiFileSystem.$anonfun$getFileStatusNoCache$1(LokiFileSystem.scala:650)
	at com.databricks.sql.io.LokiFileSystem$.withWrappedExceptions(LokiFileSystem.scala:158)
	at com.databricks.sql.io.LokiFileSystem.getFileStatusNoCache(LokiFileSystem.scala:651)
	at com.databricks.sql.io.LokiFileSystem.getFileStatus(LokiFileSystem.scala:656)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1862)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRootThrowOnError(DeltaTable.scala:468)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRoot(DeltaTable.scala:416)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRoot(DeltaTable.scala:407)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRoot(DeltaTable.scala:399)
	at com.databricks.sql.transaction.tahoe.DeltaValidation$.validateNonDeltaWrite(DeltaValidation.scala:222)
	at org.apache.spark.sql.classic.DataFrameWriter.saveInternal(DataFrameWriter.scala:186)
	at org.apache.spark.sql.classic.DataFrameWriter.save(DataFrameWriter.scala:153)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleWriteOperation(SparkConnectPlanner.scala:4519)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3748)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:517)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:405)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:331)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:796)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:796)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:124)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:118)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:123)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:795)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:331)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$execute$1(ExecuteThreadRunner.scala:196)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries(UtilizationMetrics.scala:72)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries$(UtilizationMetrics.scala:69)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.recordActiveQueries(ExecuteThreadRunner.scala:57)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:188)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$3(ExecuteThreadRunner.scala:722)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.DBRTracing$.withSpanFromParent(DBRTracing.scala:70)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:722)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:128)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:133)
	at scala.util.Using$.resource(Using.scala:296)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:132)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:721)
Caused by: com.databricks.backend.daemon.data.client.DbfsDisabledException: Public DBFS root is disabled. Access is denied on path: /tmp/delta_test_tmp/_delta_log
	at com.databricks.backend.daemon.data.client.DisabledDatabricksFileSystem.rejectOperation(DisabledDatabricksFileSystem.scala:44)
	at com.databricks.backend.daemon.data.client.DisabledDatabricksFileSystem.getFileStatus(DisabledDatabricksFileSystem.scala:127)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$getFileStatus$3(DatabricksFileSystemV2.scala:1320)
	at com.databricks.s3a.S3AExceptionUtils$.convertAWSExceptionToJavaIOException(DatabricksStreamUtils.scala:65)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$getFileStatus$2(DatabricksFileSystemV2.scala:1317)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:531)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:669)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$6(UsageLogging.scala:696)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:146)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:349)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:345)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:144)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:141)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:850)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:201)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:182)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:850)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$5(UsageLogging.scala:664)
	at com.databricks.logging.UsageLogging.withOtelSpanInContext$1(UsageLogging.scala:656)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:659)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:540)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperationWithResultTags(DatabricksFileSystemV2.scala:850)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:532)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:496)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperation(DatabricksFileSystemV2.scala:850)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.getFileStatus(DatabricksFileSystemV2.scala:1316)
	at com.databricks.backend.daemon.data.client.DBFSV2.super$getFileStatus(DatabricksFileSystemV2.scala:752)
	at com.databricks.backend.daemon.data.client.DBFSV2.$anonfun$getFileStatus$1(DatabricksFileSystemV2.scala:752)
	at com.databricks.backend.daemon.data.client.DbfsExceptionMapperImpl.withExceptionWrapping(DbfsSparkException.scala:39)
	at com.databricks.backend.daemon.data.client.DBFSV2.getFileStatus(DatabricksFileSystemV2.scala:752)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystem.getFileStatus(DatabricksFileSystem.scala:212)
	at com.databricks.sql.io.LokiFileSystem.$anonfun$getFileStatusNoCache$4(LokiFileSystem.scala:650)
	at com.databricks.sql.io.LokiFileSystem.tryWithNativeIO(LokiFileSystem.scala:622)
	at com.databricks.sql.io.LokiFileSystem.$anonfun$getFileStatusNoCache$1(LokiFileSystem.scala:650)
	at com.databricks.sql.io.LokiFileSystem$.withWrappedExceptions(LokiFileSystem.scala:158)
	at com.databricks.sql.io.LokiFileSystem.getFileStatusNoCache(LokiFileSystem.scala:651)
	at com.databricks.sql.io.LokiFileSystem.getFileStatus(LokiFileSystem.scala:656)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1862)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRootThrowOnError(DeltaTable.scala:468)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRoot(DeltaTable.scala:416)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRoot(DeltaTable.scala:407)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRoot(DeltaTable.scala:399)
	at com.databricks.sql.transaction.tahoe.DeltaValidation$.validateNonDeltaWrite(DeltaValidation.scala:222)
	at org.apache.spark.sql.classic.DataFrameWriter.saveInternal(DataFrameWriter.scala:186)
	at org.apache.spark.sql.classic.DataFrameWriter.save(DataFrameWriter.scala:153)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleWriteOperation(SparkConnectPlanner.scala:4519)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3748)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:517)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:405)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:331)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:796)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:866)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:796)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:124)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:118)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:123)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:795)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:331)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$execute$1(ExecuteThreadRunner.scala:196)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries(UtilizationMetrics.scala:72)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries$(UtilizationMetrics.scala:69)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.recordActiveQueries(ExecuteThreadRunner.scala:57)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:188)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$3(ExecuteThreadRunner.scala:722)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.DBRTracing$.withSpanFromParent(DBRTracing.scala:70)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:722)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:128)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:133)
	at scala.util.Using$.resource(Using.scala:296)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:132)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:721)

In [0]:
print("Catalogs:")
display(spark.sql("SHOW CATALOGS"))

print("Schemas:")
display(spark.sql("SHOW SCHEMAS"))

print("Volumes (if supported):")
try:
    display(spark.sql("SHOW VOLUMES"))
except Exception as e:
    print("SHOW VOLUMES not supported")
    print(e)

Catalogs:

catalog
samples
system
workspace

Schemas:

databaseName
default
information_schema

Volumes (if supported):

In [0]:
master_df.write \
    .format("delta") \
    .mode("overwrite") \
    .saveAsTable("workspace.default.customer_master")

In [0]:
# Check if the table exists
display(spark.sql("SELECT * FROM workspace.default.customer_master LIMIT 10"))

print("Total rows:")
print(spark.sql("SELECT COUNT(*) AS total_rows FROM workspace.default.customer_master").collect()[0][0])

customer_id,first_name,last_name,email,phone,city
1,Neha,Verma,invalid_email,9321819600,Jaipur
2,Ananya,Agarwal,invalid_email,9863794026,Pune
3,Krishna,Mehta,krishna.mehta3@gmail.com,9559407816,Ahmedabad
4,Diya,Agarwal,diya.agarwal4@gmail.com,9310341316,Bengaluru
5,Aditya,Mehta,aditya.mehta5@gmail.com,9192832764,Jaipur
6,Neha,Mehta,neha.mehta6@gmail.com,9305641395,Hyderabad
7,Rahul,Joshi,rahul.joshi7@gmail.com,9884969653,Pune
8,Ananya,Joshi,null,9122691669,Ahmedabad
9,Ananya,Sharma,ananya.sharma9@gmail.com,9845146270,Ahmedabad
10,Ananya,Patel,ananya.patel10@gmail.com,9489325288,Bengaluru

Total rows:
520

In [0]:
from pyspark.sql.functions import col

# Load the Delta table
master_df = spark.table("workspace.default.customer_master")

# Clean the data
clean_df = (
    master_df
    .dropDuplicates(["customer_id"])
    .filter(col("email").isNotNull())
    .filter(col("email").rlike(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"))
)

# Save cleaned data back as a new Delta table
clean_df.write \
    .format("delta") \
    .mode("overwrite") \
    .saveAsTable("workspace.default.customer_master_clean")

print("Original rows:", master_df.count())
print("Cleaned rows :", clean_df.count())

display(clean_df.limit(10))

Original rows: 520
Cleaned rows : 453

customer_id,first_name,last_name,email,phone,city
3,Krishna,Mehta,krishna.mehta3@gmail.com,9559407816,Ahmedabad
4,Diya,Agarwal,diya.agarwal4@gmail.com,9310341316,Bengaluru
5,Aditya,Mehta,aditya.mehta5@gmail.com,9192832764,Jaipur
6,Neha,Mehta,neha.mehta6@gmail.com,9305641395,Hyderabad
7,Rahul,Joshi,rahul.joshi7@gmail.com,9884969653,Pune
9,Ananya,Sharma,ananya.sharma9@gmail.com,9845146270,Ahmedabad
10,Ananya,Patel,ananya.patel10@gmail.com,9489325288,Bengaluru
11,Priya,Sharma,priya.sharma11@gmail.com,9430391171,Pune
12,Aditya,Joshi,aditya.joshi12@gmail.com,9896383465,Hyderabad
13,Vivaan,Gupta,vivaan.gupta13@gmail.com,9983930103,Delhi

In [0]:
import random
from pyspark.sql import Row

random.seed(123)

# Existing cleaned data
clean_df = spark.table("workspace.default.customer_master_clean")

# Get existing customer IDs
existing_ids = [r.customer_id for r in clean_df.select("customer_id").collect()]
update_ids = random.sample(existing_ids, 50)

cities = [
    "Delhi", "Mumbai", "Pune", "Jaipur",
    "Ahmedabad", "Bengaluru", "Chennai", "Hyderabad"
]

incremental_records = []

# 50 updates
for cid in update_ids:
    incremental_records.append(
        Row(
            customer_id=cid,
            first_name=None,
            last_name=None,
            email=None,
            phone="8" + "".join(str(random.randint(0,9)) for _ in range(9)),
            city=random.choice(cities)
        )
    )

# 50 new customers
start_id = max(existing_ids) + 1

for i in range(50):
    cid = start_id + i

    incremental_records.append(
        Row(
            customer_id=cid,
            first_name=f"New{cid}",
            last_name="Customer",
            email=f"new{cid}@gmail.com",
            phone="9" + "".join(str(random.randint(0,9)) for _ in range(9)),
            city=random.choice(cities)
        )
    )

incremental_df = spark.createDataFrame(incremental_records)

incremental_df.write \
    .format("delta") \
    .mode("overwrite") \
    .saveAsTable("workspace.default.customer_incremental")

print("Incremental rows:", incremental_df.count())

display(incremental_df.limit(10))

Incremental rows: 100

customer_id,first_name,last_name,email,phone,city
259,null,null,null,8873989506,Chennai
115,null,null,null,8897865802,Mumbai
245,null,null,null,8742558617,Chennai
382,null,null,null,8950391505,Jaipur
426,null,null,null,8688047387,Pune
167,null,null,null,8287670027,Jaipur
412,null,null,null,8045466019,Mumbai
401,null,null,null,8851160861,Chennai
70,null,null,null,8054708565,Delhi
356,null,null,null,8261253108,Chennai

In [0]:
from delta.tables import DeltaTable
from pyspark.sql.functions import coalesce

# Load Delta table
delta_table = DeltaTable.forName(spark, "workspace.default.customer_master_clean")

# Source data
incremental_df = spark.table("workspace.default.customer_incremental")

# MERGE operation
(
    delta_table.alias("target")
    .merge(
        incremental_df.alias("source"),
        "target.customer_id = source.customer_id"
    )
    .whenMatchedUpdate(
        set={
            "first_name": "coalesce(source.first_name, target.first_name)",
            "last_name": "coalesce(source.last_name, target.last_name)",
            "email": "coalesce(source.email, target.email)",
            "phone": "coalesce(source.phone, target.phone)",
            "city": "coalesce(source.city, target.city)"
        }
    )
    .whenNotMatchedInsert(
        values={
            "customer_id": "source.customer_id",
            "first_name": "source.first_name",
            "last_name": "source.last_name",
            "email": "source.email",
            "phone": "source.phone",
            "city": "source.city"
        }
    )
    .execute()
)

print("MERGE completed successfully!")

MERGE completed successfully!

In [0]:
from pyspark.sql.functions import countDistinct

final_df = spark.table("workspace.default.customer_master_clean")

print("Final Row Count:")
print(final_df.count())

print("\nDistinct Customer IDs:")
print(final_df.select(countDistinct("customer_id")).collect()[0][0])

print("\nDuplicate Customer IDs:")
duplicates = (
    final_df.groupBy("customer_id")
    .count()
    .filter("count > 1")
)

print(duplicates.count())

display(duplicates)

Final Row Count:
503

Distinct Customer IDs:
503

Duplicate Customer IDs:
0

In [0]:
final_df = spark.table("workspace.default.customer_master_clean")

print("=" * 50)
print("DELTA LAKE ASSIGNMENT SUMMARY")
print("=" * 50)

print(f"Initial Dataset Rows      : 520")
print(f"Rows After Cleaning       : 453")
print(f"Incremental Dataset Rows  : 100")
print(f"Final Dataset Rows        : {final_df.count()}")

print("\nMERGE Operation : SUCCESS")
print("Duplicate Check : PASSED")
print("Data Validation : PASSED")

print("\nFinal Dataset Preview")

display(final_df.orderBy("customer_id"))

==================================================
DELTA LAKE ASSIGNMENT SUMMARY
==================================================
Initial Dataset Rows      : 520
Rows After Cleaning       : 453
Incremental Dataset Rows  : 100
Final Dataset Rows        : 503

MERGE Operation : SUCCESS
Duplicate Check : PASSED
Data Validation : PASSED

Final Dataset Preview

customer_id,first_name,last_name,email,phone,city
3,Krishna,Mehta,krishna.mehta3@gmail.com,9559407816,Ahmedabad
4,Diya,Agarwal,diya.agarwal4@gmail.com,9310341316,Bengaluru
5,Aditya,Mehta,aditya.mehta5@gmail.com,8704271217,Bengaluru
6,Neha,Mehta,neha.mehta6@gmail.com,9305641395,Hyderabad
7,Rahul,Joshi,rahul.joshi7@gmail.com,9884969653,Pune
9,Ananya,Sharma,ananya.sharma9@gmail.com,8833546081,Jaipur
10,Ananya,Patel,ananya.patel10@gmail.com,9489325288,Bengaluru
11,Priya,Sharma,priya.sharma11@gmail.com,9430391171,Pune
12,Aditya,Joshi,aditya.joshi12@gmail.com,9896383465,Hyderabad
13,Vivaan,Gupta,vivaan.gupta13@gmail.com,9983930103,Delhi
14,Diya,Mehta,diya.mehta14@gmail.com,9738299737,Jaipur
15,Vivaan,Verma,vivaan.verma15@gmail.com,9670106513,Hyderabad
16,Aditya,Jain,aditya.jain16@gmail.com,9178108013,Hyderabad
17,Priya,Gupta,priya.gupta17@gmail.com,9260647468,Hyderabad
18,Aditya,Gupta,aditya.gupta18@gmail.com,9980500978,Pune
19,Aarav,Kapoor,aarav.kapoor19@gmail.com,null,Mumbai
20,Rahul,Agarwal,rahul.agarwal20@gmail.com,9435346247,Mumbai
21,Aarav,Joshi,aarav.joshi21@gmail.com,9118384251,Bengaluru
22,Arjun,Patel,arjun.patel22@gmail.com,9498084124,Mumbai
23,Pooja,Kapoor,pooja.kapoor23@gmail.com,9353487401,Ahmedabad
24,Aarav,Sharma,aarav.sharma24@gmail.com,9427868011,Pune
25,Ananya,Sharma,ananya.sharma25@gmail.com,9262045053,Mumbai
26,Rohan,Kapoor,rohan.kapoor26@gmail.com,8417953747,Bengaluru
27,Kavya,Gupta,kavya.gupta27@gmail.com,9160733754,Jaipur
28,Krishna,Sharma,krishna.sharma28@gmail.com,8148950609,Chennai
29,Aditya,Agarwal,aditya.agarwal29@gmail.com,9196556981,Jaipur
31,Ananya,Singh,ananya.singh31@gmail.com,9482366299,Delhi
32,Arjun,Singh,arjun.singh32@gmail.com,9957773872,Ahmedabad
33,Ananya,Agarwal,ananya.agarwal33@gmail.com,9343320037,Mumbai
34,Priya,Jain,priya.jain34@gmail.com,9676320163,Hyderabad
35,Aarav,Kapoor,aarav.kapoor35@gmail.com,9727889579,Chennai
36,Diya,Kapoor,diya.kapoor36@gmail.com,9774348734,Ahmedabad
37,Krishna,Singh,krishna.singh37@gmail.com,9122362316,Hyderabad
38,Rahul,Sharma,rahul.sharma38@gmail.com,9909670546,Chennai
39,Ananya,Kapoor,ananya.kapoor39@gmail.com,9734670656,Hyderabad
40,Aditya,Agarwal,aditya.agarwal40@gmail.com,9990162720,Bengaluru
41,Krishna,Joshi,krishna.joshi41@gmail.com,9646417080,Bengaluru
42,Krishna,Verma,krishna.verma42@gmail.com,9033092327,Jaipur
43,Priya,Singh,priya.singh43@gmail.com,9912419049,Chennai
44,Rahul,Gupta,rahul.gupta44@gmail.com,9314919058,Bengaluru
46,Sneha,Kapoor,sneha.kapoor46@gmail.com,9945314737,Chennai
47,Rohan,Sharma,rohan.sharma47@gmail.com,null,Jaipur
48,Vivaan,Gupta,vivaan.gupta48@gmail.com,9377701436,Ahmedabad
49,Neha,Agarwal,neha.agarwal49@gmail.com,9568557444,Jaipur
50,Rohan,Verma,rohan.verma50@gmail.com,9233749894,Jaipur
51,Arjun,Gupta,arjun.gupta51@gmail.com,8539078949,Delhi
52,Sneha,Singh,sneha.singh52@gmail.com,9204711671,Delhi
53,Aditya,Patel,aditya.patel53@gmail.com,9131869993,Chennai
54,Priya,Joshi,priya.joshi54@gmail.com,9649909133,Mumbai
55,Aditya,Gupta,aditya.gupta55@gmail.com,9067974034,Hyderabad
56,Vivaan,Gupta,vivaan.gupta56@gmail.com,9936183242,Pune
57,Kavya,Singh,kavya.singh57@gmail.com,9471746488,Mumbai
58,Sneha,Sharma,sneha.sharma58@gmail.com,8563144265,Chennai
59,Priya,Kapoor,priya.kapoor59@gmail.com,9296717565,Mumbai
60,Diya,Patel,diya.patel60@gmail.com,9468071545,Chennai
62,Krishna,Singh,krishna.singh62@gmail.com,null,Chennai
63,Vivaan,Gupta,vivaan.gupta63@gmail.com,8018195136,Pune
64,Priya,Kapoor,priya.kapoor64@gmail.com,9982146584,Ahmedabad
65,Pooja,Singh,pooja.singh65@gmail.com,9727875588,Bengaluru
66,Diya,Gupta,diya.gupta66@gmail.com,9636057662,Delhi
67,Aditya,Kapoor,aditya.kapoor67@gmail.com,9171870262,Ahmedabad
68,Rohan,Agarwal,rohan.agarwal68@gmail.com,9586578091,Ahmedabad
69,Krishna,Verma,krishna.verma69@gmail.com,9172400504,Chennai
70,Aditya,Gupta,aditya.gupta70@gmail.com,8054708565,Delhi
71,Krishna,Joshi,krishna.joshi71@gmail.com,9074821759,Chennai
72,Pooja,Singh,pooja.singh72@gmail.com,9671369594,Ahmedabad
73,Aarav,Jain,aarav.jain73@gmail.com,9097439533,Pune
74,Neha,Verma,neha.verma74@gmail.com,9470952145,Pune
75,Krishna,Patel,krishna.patel75@gmail.com,9588424745,Hyderabad
76,Vivaan,Patel,vivaan.patel76@gmail.com,9685160481,Ahmedabad
77,Sneha,Jain,sneha.jain77@gmail.com,9137098593,Hyderabad
78,Pooja,Singh,pooja.singh78@gmail.com,9004711382,Bengaluru
79,Neha,Kapoor,neha.kapoor79@gmail.com,9261796405,Hyderabad
80,Krishna,Mehta,krishna.mehta80@gmail.com,9850643171,Delhi
81,Aarav,Mehta,aarav.mehta81@gmail.com,9931839335,Delhi
82,Arjun,Patel,arjun.patel82@gmail.com,null,Ahmedabad
83,Aarav,Patel,aarav.patel83@gmail.com,9177589178,Delhi
84,Pooja,Kapoor,pooja.kapoor84@gmail.com,9007661771,Bengaluru
85,Sneha,Patel,sneha.patel85@gmail.com,9985698478,Mumbai
86,Kavya,Verma,kavya.verma86@gmail.com,9836736576,Mumbai
87,Rohan,Jain,rohan.jain87@gmail.com,8296602705,Hyderabad
88,Sneha,Kapoor,sneha.kapoor88@gmail.com,9656049451,Jaipur
89,Aditya,Joshi,aditya.joshi89@gmail.com,9851493689,Delhi
91,Vivaan,Kapoor,vivaan.kapoor91@gmail.com,8233303316,Delhi
92,Neha,Verma,neha.verma92@gmail.com,9797643815,Ahmedabad
93,Neha,Agarwal,neha.agarwal93@gmail.com,8834773481,Mumbai
94,Arjun,Mehta,arjun.mehta94@gmail.com,9622683885,Delhi
95,Rahul,Sharma,rahul.sharma95@gmail.com,null,Bengaluru
96,Aditya,Agarwal,aditya.agarwal96@gmail.com,9516136968,Ahmedabad
97,Pooja,Mehta,pooja.mehta97@gmail.com,9181883552,Pune
98,Arjun,Gupta,arjun.gupta98@gmail.com,9127799799,Bengaluru
99,Aditya,Joshi,aditya.joshi99@gmail.com,9449058147,Delhi
100,Rohan,Singh,rohan.singh100@gmail.com,9199867980,Jaipur
101,Rohan,Agarwal,rohan.agarwal101@gmail.com,9071518203,Hyderabad
102,Ananya,Kapoor,ananya.kapoor102@gmail.com,8090723048,Pune
103,Arjun,Singh,arjun.singh103@gmail.com,9925192546,Mumbai
104,Arjun,Kapoor,arjun.kapoor104@gmail.com,9281685054,Jaipur
105,Rohan,Joshi,rohan.joshi105@gmail.com,9214188805,Pune
106,Sneha,Jain,sneha.jain106@gmail.com,9927065379,Hyderabad
107,Krishna,Kapoor,krishna.kapoor107@gmail.com,9735977468,Pune
108,Diya,Gupta,diya.gupta108@gmail.com,9407581814,Pune
109,Arjun,Joshi,arjun.joshi109@gmail.com,9613750606,Jaipur
111,Vivaan,Sharma,vivaan.sharma111@gmail.com,null,Chennai
112,Neha,Agarwal,neha.agarwal112@gmail.com,9798089324,Bengaluru
113,Krishna,Agarwal,krishna.agarwal113@gmail.com,null,Hyderabad
114,Aarav,Jain,aarav.jain114@gmail.com,null,Bengaluru
115,Diya,Patel,diya.patel115@gmail.com,8897865802,Mumbai
116,Rohan,Singh,rohan.singh116@gmail.com,9874034505,Bengaluru
117,Rahul,Jain,rahul.jain117@gmail.com,9652775841,Mumbai
118,Rahul,Agarwal,rahul.agarwal118@gmail.com,9451154479,Pune
120,Aarav,Patel,aarav.patel120@gmail.com,null,Pune
121,Neha,Joshi,neha.joshi121@gmail.com,9192856543,Delhi
122,Pooja,Patel,pooja.patel122@gmail.com,9814473947,Pune
123,Diya,Verma,diya.verma123@gmail.com,9715518844,Pune
124,Kavya,Mehta,kavya.mehta124@gmail.com,9323705895,Pune
125,Sneha,Verma,sneha.verma125@gmail.com,8049756382,Delhi
126,Aditya,Kapoor,aditya.kapoor126@gmail.com,9268018242,Jaipur
127,Rohan,Kapoor,rohan.kapoor127@gmail.com,9438424981,Pune
128,Sneha,Agarwal,sneha.agarwal128@gmail.com,9959001094,Chennai
129,Sneha,Sharma,sneha.sharma129@gmail.com,9447364710,Chennai
130,Priya,Joshi,priya.joshi130@gmail.com,9555625881,Hyderabad
131,Vivaan,Singh,vivaan.singh131@gmail.com,9046963259,Jaipur
132,Kavya,Patel,kavya.patel132@gmail.com,9747016873,Bengaluru
133,Aarav,Sharma,aarav.sharma133@gmail.com,9748016245,Bengaluru
134,Aarav,Jain,aarav.jain134@gmail.com,9584168784,Mumbai
135,Aditya,Verma,aditya.verma135@gmail.com,null,Delhi
136,Aditya,Mehta,aditya.mehta136@gmail.com,9298259526,Ahmedabad
137,Sneha,Mehta,sneha.mehta137@gmail.com,8746028588,Pune
138,Sneha,Joshi,sneha.joshi138@gmail.com,9993097289,Chennai
140,Diya,Sharma,diya.sharma140@gmail.com,9857865278,Bengaluru
141,Neha,Singh,neha.singh141@gmail.com,9348434437,Bengaluru
142,Ananya,Singh,ananya.singh142@gmail.com,9866524041,Hyderabad
143,Neha,Singh,neha.singh143@gmail.com,9848421993,Jaipur
144,Neha,Gupta,neha.gupta144@gmail.com,8133567488,Pune
145,Rohan,Singh,rohan.singh145@gmail.com,9193802620,Chennai
146,Kavya,Joshi,kavya.joshi146@gmail.com,9400499154,Hyderabad
147,Aditya,Kapoor,aditya.kapoor147@gmail.com,9152742054,Jaipur
148,Aditya,Agarwal,aditya.agarwal148@gmail.com,9685161227,Jaipur
149,Aarav,Singh,aarav.singh149@gmail.com,9454990453,Mumbai
150,Priya,Singh,priya.singh150@gmail.com,8378945021,Delhi
151,Rahul,Kapoor,rahul.kapoor151@gmail.com,9339187851,Mumbai
152,Aarav,Kapoor,aarav.kapoor152@gmail.com,9822587139,Hyderabad
153,Kavya,Sharma,kavya.sharma153@gmail.com,9790874064,Jaipur
155,Rohan,Jain,rohan.jain155@gmail.com,9661825128,Pune
156,Pooja,Gupta,pooja.gupta156@gmail.com,9478686337,Ahmedabad
158,Krishna,Sharma,krishna.sharma158@gmail.com,9302843959,Bengaluru
159,Krishna,Singh,krishna.singh159@gmail.com,9836440892,Chennai
161,Krishna,Gupta,krishna.gupta161@gmail.com,9708668826,Jaipur
162,Rohan,Verma,rohan.verma162@gmail.com,9183046990,Jaipur
163,Kavya,Agarwal,kavya.agarwal163@gmail.com,9735403317,Jaipur
164,Rahul,Gupta,rahul.gupta164@gmail.com,9678544587,Hyderabad
165,Kavya,Mehta,kavya.mehta165@gmail.com,9609320489,Chennai
166,Arjun,Patel,arjun.patel166@gmail.com,9937854777,Bengaluru
167,Aditya,Patel,aditya.patel167@gmail.com,8287670027,Jaipur
169,Aarav,Kapoor,aarav.kapoor169@gmail.com,9408621182,Ahmedabad
170,Diya,Mehta,diya.mehta170@gmail.com,9567933410,Chennai
171,Rahul,Kapoor,rahul.kapoor171@gmail.com,9217659180,Hyderabad
172,Arjun,Sharma,arjun.sharma172@gmail.com,8158828277,Chennai
173,Vivaan,Singh,vivaan.singh173@gmail.com,8461948818,Mumbai
174,Diya,Verma,diya.verma174@gmail.com,9965047735,Chennai
175,Rahul,Patel,rahul.patel175@gmail.com,9194311426,Pune
176,Pooja,Jain,pooja.jain176@gmail.com,9047541212,Chennai
177,Vivaan,Sharma,vivaan.sharma177@gmail.com,9995604661,Jaipur
178,Sneha,Kapoor,sneha.kapoor178@gmail.com,9244472126,Ahmedabad
179,Priya,Verma,priya.verma179@gmail.com,9799371240,Bengaluru
180,Diya,Agarwal,diya.agarwal180@gmail.com,9756924593,Pune
181,Rahul,Mehta,rahul.mehta181@gmail.com,9793564651,Jaipur
182,Sneha,Kapoor,sneha.kapoor182@gmail.com,9073741672,Jaipur
183,Arjun,Patel,arjun.patel183@gmail.com,9179796886,Bengaluru
184,Pooja,Kapoor,pooja.kapoor184@gmail.com,9135290965,Chennai
185,Vivaan,Sharma,vivaan.sharma185@gmail.com,9889937567,Pune
186,Rohan,Sharma,rohan.sharma186@gmail.com,9112545738,Hyderabad
187,Vivaan,Joshi,vivaan.joshi187@gmail.com,9140105123,Pune
188,Rohan,Kapoor,rohan.kapoor188@gmail.com,9622660937,Chennai
189,Aarav,Gupta,aarav.gupta189@gmail.com,9191825537,Hyderabad
190,Ananya,Mehta,ananya.mehta190@gmail.com,9915579249,Pune
191,Rohan,Verma,rohan.verma191@gmail.com,9528669296,Hyderabad
192,Neha,Kapoor,neha.kapoor192@gmail.com,9282742257,Bengaluru
193,Aarav,Joshi,aarav.joshi193@gmail.com,8655375326,Delhi
194,Kavya,Gupta,kavya.gupta194@gmail.com,9842797881,Ahmedabad
195,Kavya,Kapoor,kavya.kapoor195@gmail.com,8712057333,Chennai
196,Diya,Verma,diya.verma196@gmail.com,8842465285,Mumbai
197,Kavya,Sharma,kavya.sharma197@gmail.com,9982544948,Mumbai
198,Aditya,Jain,aditya.jain198@gmail.com,9223253672,Ahmedabad
199,Neha,Jain,neha.jain199@gmail.com,null,Mumbai
200,Pooja,Joshi,pooja.joshi200@gmail.com,9186363745,Bengaluru
201,Ananya,Agarwal,ananya.agarwal201@gmail.com,9500170127,Chennai
202,Krishna,Patel,krishna.patel202@gmail.com,9415415206,Jaipur
204,Diya,Jain,diya.jain204@gmail.com,9361115542,Pune
205,Neha,Patel,neha.patel205@gmail.com,9927532697,Mumbai
206,Vivaan,Patel,vivaan.patel206@gmail.com,9656523413,Ahmedabad
207,Kavya,Sharma,kavya.sharma207@gmail.com,9438983640,Jaipur
208,Priya,Jain,priya.jain208@gmail.com,9918055269,Pune
209,Kavya,Joshi,kavya.joshi209@gmail.com,9091043006,Chennai
210,Rahul,Jain,rahul.jain210@gmail.com,9924141832,Chennai
211,Sneha,Verma,sneha.verma211@gmail.com,9303161799,Pune
212,Vivaan,Sharma,vivaan.sharma212@gmail.com,9275884252,Ahmedabad
214,Priya,Agarwal,priya.agarwal214@gmail.com,null,Bengaluru
215,Rahul,Patel,rahul.patel215@gmail.com,9086353654,Bengaluru
216,Vivaan,Kapoor,vivaan.kapoor216@gmail.com,9380617445,Hyderabad
217,Aarav,Mehta,aarav.mehta217@gmail.com,9493759738,Jaipur
219,Rahul,Joshi,rahul.joshi219@gmail.com,9241038657,Mumbai
220,Sneha,Verma,sneha.verma220@gmail.com,9619906234,Bengaluru
221,Kavya,Jain,kavya.jain221@gmail.com,9574313291,Pune
222,Priya,Joshi,priya.joshi222@gmail.com,9537474112,Ahmedabad
224,Aarav,Jain,aarav.jain224@gmail.com,9831712100,Jaipur
225,Aditya,Gupta,aditya.gupta225@gmail.com,9199410137,Mumbai
226,Diya,Mehta,diya.mehta226@gmail.com,9029667066,Jaipur
227,Aditya,Singh,aditya.singh227@gmail.com,9099934768,Mumbai
228,Arjun,Jain,arjun.jain228@gmail.com,9838065787,Bengaluru
229,Rahul,Singh,rahul.singh229@gmail.com,9304078593,Mumbai
230,Krishna,Gupta,krishna.gupta230@gmail.com,9039652239,Bengaluru
231,Sneha,Sharma,sneha.sharma231@gmail.com,9992937842,Mumbai
233,Sneha,Patel,sneha.patel233@gmail.com,9515691545,Pune
234,Pooja,Jain,pooja.jain234@gmail.com,9528953926,Ahmedabad
235,Aditya,Patel,aditya.patel235@gmail.com,9969029593,Mumbai
236,Priya,Patel,priya.patel236@gmail.com,9552157043,Mumbai
237,Rohan,Singh,rohan.singh237@gmail.com,9067626765,Mumbai
238,Diya,Joshi,diya.joshi238@gmail.com,9327104054,Mumbai
239,Rohan,Patel,rohan.patel239@gmail.com,9181599706,Pune
240,Sneha,Jain,sneha.jain240@gmail.com,9336884443,Chennai
241,Sneha,Kapoor,sneha.kapoor241@gmail.com,null,Pune
242,Neha,Singh,neha.singh242@gmail.com,9146774186,Chennai
243,Rohan,Patel,rohan.patel243@gmail.com,9743490211,Chennai
244,Kavya,Agarwal,kavya.agarwal244@gmail.com,9686879374,Delhi
245,Ananya,Agarwal,ananya.agarwal245@gmail.com,8742558617,Chennai
246,Neha,Jain,neha.jain246@gmail.com,9294511686,Ahmedabad
248,Vivaan,Agarwal,vivaan.agarwal248@gmail.com,8237636002,Mumbai
249,Rahul,Patel,rahul.patel249@gmail.com,null,Ahmedabad
250,Arjun,Singh,arjun.singh250@gmail.com,9132475469,Jaipur
251,Priya,Gupta,priya.gupta251@gmail.com,9785082148,Delhi
252,Aditya,Gupta,aditya.gupta252@gmail.com,9030705345,Chennai
253,Neha,Verma,neha.verma253@gmail.com,9797279855,Ahmedabad
254,Pooja,Verma,pooja.verma254@gmail.com,null,Delhi
255,Priya,Patel,priya.patel255@gmail.com,9034944665,Jaipur
256,Priya,Singh,priya.singh256@gmail.com,9691085899,Mumbai
257,Priya,Verma,priya.verma257@gmail.com,9544432830,Chennai
258,Neha,Mehta,neha.mehta258@gmail.com,9744666099,Bengaluru
259,Pooja,Gupta,pooja.gupta259@gmail.com,8873989506,Chennai
260,Pooja,Kapoor,pooja.kapoor260@gmail.com,9513534655,Ahmedabad
261,Priya,Verma,priya.verma261@gmail.com,9999173816,Chennai
262,Aarav,Patel,aarav.patel262@gmail.com,9697252175,Pune
265,Arjun,Patel,arjun.patel265@gmail.com,9421044789,Chennai
266,Neha,Patel,neha.patel266@gmail.com,9532603323,Pune
267,Vivaan,Mehta,vivaan.mehta267@gmail.com,null,Mumbai
268,Rahul,Joshi,rahul.joshi268@gmail.com,9723046184,Pune
269,Rahul,Verma,rahul.verma269@gmail.com,9411739348,Bengaluru
271,Aditya,Verma,aditya.verma271@gmail.com,9143744701,Delhi
272,Diya,Singh,diya.singh272@gmail.com,8581853951,Ahmedabad
273,Pooja,Verma,pooja.verma273@gmail.com,9166746762,Delhi
274,Diya,Patel,diya.patel274@gmail.com,9797296590,Pune
275,Priya,Joshi,priya.joshi275@gmail.com,8710966852,Hyderabad
276,Ananya,Kapoor,ananya.kapoor276@gmail.com,null,Pune
277,Ananya,Joshi,ananya.joshi277@gmail.com,9175354083,Chennai
278,Rahul,Gupta,rahul.gupta278@gmail.com,9971775170,Chennai
279,Aarav,Kapoor,aarav.kapoor279@gmail.com,9994883755,Jaipur
280,Diya,Joshi,diya.joshi280@gmail.com,9975711305,Ahmedabad
281,Ananya,Kapoor,ananya.kapoor281@gmail.com,9272614933,Chennai
282,Krishna,Joshi,krishna.joshi282@gmail.com,8081134328,Delhi
284,Ananya,Jain,ananya.jain284@gmail.com,9346547226,Ahmedabad
285,Diya,Kapoor,diya.kapoor285@gmail.com,8890785453,Chennai
286,Pooja,Verma,pooja.verma286@gmail.com,null,Pune
287,Aarav,Sharma,aarav.sharma287@gmail.com,9244204380,Hyderabad
288,Vivaan,Agarwal,vivaan.agarwal288@gmail.com,9386384066,Bengaluru
290,Neha,Verma,neha.verma290@gmail.com,9816064842,Ahmedabad
291,Aarav,Mehta,aarav.mehta291@gmail.com,9025909479,Mumbai
292,Kavya,Mehta,kavya.mehta292@gmail.com,9818268861,Jaipur
293,Neha,Mehta,neha.mehta293@gmail.com,9987801573,Jaipur
294,Aarav,Mehta,aarav.mehta294@gmail.com,9164840858,Hyderabad
295,Priya,Sharma,priya.sharma295@gmail.com,9581128801,Jaipur
296,Diya,Jain,diya.jain296@gmail.com,9612075011,Ahmedabad
297,Ananya,Verma,ananya.verma297@gmail.com,9466766506,Delhi
298,Neha,Agarwal,neha.agarwal298@gmail.com,9015814491,Hyderabad
300,Aarav,Kapoor,aarav.kapoor300@gmail.com,9009968814,Bengaluru
301,Krishna,Jain,krishna.jain301@gmail.com,9222394312,Delhi
302,Diya,Kapoor,diya.kapoor302@gmail.com,9414139755,Jaipur
303,Vivaan,Singh,vivaan.singh303@gmail.com,9577594929,Bengaluru
305,Priya,Kapoor,priya.kapoor305@gmail.com,8629571983,Chennai
306,Diya,Agarwal,diya.agarwal306@gmail.com,9308488725,Ahmedabad
307,Aditya,Joshi,aditya.joshi307@gmail.com,9580392827,Pune
309,Rahul,Joshi,rahul.joshi309@gmail.com,9051844989,Chennai
310,Rohan,Agarwal,rohan.agarwal310@gmail.com,9846386557,Delhi
311,Ananya,Patel,ananya.patel311@gmail.com,9843222591,Chennai
312,Kavya,Mehta,kavya.mehta312@gmail.com,9773926030,Pune
314,Vivaan,Gupta,vivaan.gupta314@gmail.com,9723692929,Ahmedabad
315,Aditya,Mehta,aditya.mehta315@gmail.com,9136621038,Chennai
316,Diya,Patel,diya.patel316@gmail.com,8363866836,Mumbai
317,Kavya,Jain,kavya.jain317@gmail.com,9086376599,Pune
318,Arjun,Joshi,arjun.joshi318@gmail.com,9149864300,Mumbai
319,Ananya,Sharma,ananya.sharma319@gmail.com,9565126944,Chennai
320,Sneha,Mehta,sneha.mehta320@gmail.com,9636887258,Ahmedabad
321,Arjun,Agarwal,arjun.agarwal321@gmail.com,8627202150,Mumbai
323,Pooja,Jain,pooja.jain323@gmail.com,9849027703,Ahmedabad
324,Krishna,Sharma,krishna.sharma324@gmail.com,9392053021,Chennai
325,Rohan,Jain,rohan.jain325@gmail.com,9011848955,Ahmedabad
326,Krishna,Agarwal,krishna.agarwal326@gmail.com,9690426818,Ahmedabad
327,Rohan,Verma,rohan.verma327@gmail.com,9894769735,Hyderabad
328,Neha,Joshi,neha.joshi328@gmail.com,9714163356,Delhi
329,Pooja,Singh,pooja.singh329@gmail.com,9518275539,Jaipur
330,Priya,Gupta,priya.gupta330@gmail.com,9433339521,Mumbai
331,Neha,Joshi,neha.joshi331@gmail.com,9807595794,Ahmedabad
332,Rahul,Gupta,rahul.gupta332@gmail.com,9867808562,Mumbai
333,Pooja,Kapoor,pooja.kapoor333@gmail.com,9036915594,Ahmedabad
334,Krishna,Singh,krishna.singh334@gmail.com,9527636556,Pune
335,Sneha,Patel,sneha.patel335@gmail.com,9143866322,Delhi
336,Aditya,Jain,aditya.jain336@gmail.com,9885744890,Pune
337,Aarav,Gupta,aarav.gupta337@gmail.com,9175455884,Chennai
338,Vivaan,Mehta,vivaan.mehta338@gmail.com,9399824558,Hyderabad
339,Vivaan,Jain,vivaan.jain339@gmail.com,9225699611,Jaipur
340,Rohan,Mehta,rohan.mehta340@gmail.com,9964759876,Delhi
341,Aditya,Gupta,aditya.gupta341@gmail.com,8914115045,Pune
342,Ananya,Verma,ananya.verma342@gmail.com,9164334722,Pune
343,Aarav,Sharma,aarav.sharma343@gmail.com,9577848728,Hyderabad
344,Neha,Agarwal,neha.agarwal344@gmail.com,9845783174,Ahmedabad
346,Kavya,Singh,kavya.singh346@gmail.com,9853686632,Chennai
347,Diya,Jain,diya.jain347@gmail.com,9389448463,Pune
348,Aditya,Singh,aditya.singh348@gmail.com,9749735020,Delhi
349,Aditya,Verma,aditya.verma349@gmail.com,9703120735,Hyderabad
351,Diya,Jain,diya.jain351@gmail.com,9367303718,Jaipur
352,Priya,Jain,priya.jain352@gmail.com,9520881474,Delhi
353,Diya,Gupta,diya.gupta353@gmail.com,null,Delhi
354,Sneha,Joshi,sneha.joshi354@gmail.com,9132719500,Pune
355,Pooja,Kapoor,pooja.kapoor355@gmail.com,9358573065,Ahmedabad
356,Aarav,Joshi,aarav.joshi356@gmail.com,8261253108,Chennai
357,Vivaan,Kapoor,vivaan.kapoor357@gmail.com,8984685526,Delhi
358,Kavya,Agarwal,kavya.agarwal358@gmail.com,9863878294,Bengaluru
359,Vivaan,Verma,vivaan.verma359@gmail.com,9220317310,Chennai
360,Neha,Joshi,neha.joshi360@gmail.com,9405391037,Mumbai
361,Priya,Sharma,priya.sharma361@gmail.com,9650948014,Jaipur
362,Ananya,Verma,ananya.verma362@gmail.com,9633839288,Mumbai
363,Kavya,Agarwal,kavya.agarwal363@gmail.com,9612286852,Hyderabad
364,Rohan,Mehta,rohan.mehta364@gmail.com,8604023521,Pune
365,Rohan,Joshi,rohan.joshi365@gmail.com,8945505804,Mumbai