In [1]:
import sys
print(sys.executable)

e:\celebal internship\week2\w8\.venv\Scripts\python.exe

In [3]:
import pandas as pd
from faker import Faker

print("Everything is working!")

Everything is working!

In [4]:
import pandas as pd
import random
import uuid

from faker import Faker
from datetime import datetime, timedelta

In [5]:
fake = Faker("en_IN")

random.seed(42)
Faker.seed(42)

In [6]:
NUM_CUSTOMERS = 600
NUM_PRODUCTS = 500
NUM_ORDERS = 700
NUM_ORDER_ITEMS = 2500

In [7]:
customer_types = [
    "REGULAR",
    "PREMIUM",
    "VIP"
]

categories = {
    "Electronics": [
        "Mobile",
        "Laptop",
        "Accessories"
    ],
    "Clothing": [
        "Men",
        "Women",
        "Kids"
    ],
    "Home": [
        "Kitchen",
        "Furniture",
        "Decor"
    ],
    "Books": [
        "Fiction",
        "Education",
        "Comics"
    ]
}

regions = [
    "North",
    "South",
    "East",
    "West"
]

order_status = [
    "PLACED",
    "SHIPPED",
    "DELIVERED",
    "CANCELLED",
    "RETURNED"
]

In [8]:
customers = []

for i in range(1, NUM_CUSTOMERS + 1):

    customer_id = f"CUST{i:04d}"

    customer_name = fake.name()

    email = fake.email()

    registration_date = fake.date_between(
        start_date="-3y",
        end_date="today"
    )

    customer_type = random.choices(
        customer_types,
        weights=[70, 20, 10],
        k=1
    )[0]

    customers.append({
        "customer_id": customer_id,
        "customer_name": customer_name,
        "email": email,
        "registration_date": registration_date,
        "customer_type": customer_type
    })

In [9]:
num_invalid = int(NUM_CUSTOMERS * 0.02)

invalid_indices = random.sample(range(NUM_CUSTOMERS), num_invalid)

for idx in invalid_indices:

    email = customers[idx]["email"]

    if random.choice([True, False]):
        customers[idx]["email"] = email.replace("@", "")
    else:
        customers[idx]["email"] = email.split("@")[0] + "@"

In [10]:
customers_df = pd.DataFrame(customers)

customers_df.head()

,customer_id,customer_name,email,registration_date,customer_type
0,CUST0001,Aryan Maharaj,udantdewan@example.net,2023-12-18,REGULAR
1,CUST0002,Pahal Balay,chandertejas@example.org,2025-09-04,REGULAR
2,CUST0003,Rushil Saini,saumyamall@example.org,2024-03-16,REGULAR
3,CUST0004,Harini Mall,tanveernayar@example.org,2023-12-03,REGULAR
4,CUST0005,Gunbir Parmer,aishani07@example.net,2024-01-21,PREMIUM

In [11]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        600 non-null    str
 1   customer_name      600 non-null    str
 2   email              600 non-null    str
 3   registration_date  600 non-null    object
 4   customer_type      600 non-null    str
dtypes: object(1), str(4)
memory usage: 23.6+ KB

In [12]:
customers_df["customer_type"].value_counts()

customer_type
REGULAR    415
PREMIUM    126
VIP         59
Name: count, dtype: int64

In [13]:
customers_df.to_csv(
    "../data/raw/customers.csv",
    index=False
)

print("customers.csv generated successfully!")

customers.csv generated successfully!

In [14]:
product_catalog = {
    "Electronics": {
        "Mobile": [
            "iPhone 15",
            "Galaxy S24",
            "OnePlus 13",
            "Pixel 9",
            "Nothing Phone"
        ],
        "Laptop": [
            "MacBook Air",
            "Dell XPS",
            "HP Pavilion",
            "Lenovo ThinkPad",
            "Asus Vivobook"
        ],
        "Accessories": [
            "Wireless Mouse",
            "Bluetooth Speaker",
            "Power Bank",
            "USB Hub",
            "Keyboard"
        ]
    },

    "Clothing": {
        "Men": [
            "T-Shirt",
            "Jeans",
            "Shirt",
            "Jacket",
            "Hoodie"
        ],
        "Women": [
            "Kurti",
            "Dress",
            "Top",
            "Jeans",
            "Sweater"
        ],
        "Kids": [
            "Kids T-Shirt",
            "Kids Shorts",
            "Kids Jacket",
            "Kids Shoes"
        ]
    },

    "Home": {
        "Kitchen": [
            "Mixer",
            "Pressure Cooker",
            "Knife Set",
            "Frying Pan"
        ],
        "Furniture": [
            "Office Chair",
            "Dining Table",
            "Bookshelf",
            "Sofa"
        ],
        "Decor": [
            "Wall Clock",
            "Flower Vase",
            "Lamp",
            "Mirror"
        ]
    },

    "Books": {
        "Education": [
            "Python Programming",
            "Data Structures",
            "Operating Systems",
            "DBMS"
        ],
        "Fiction": [
            "Mystery Novel",
            "Fantasy Book",
            "Thriller Novel"
        ],
        "Comics": [
            "Marvel Comic",
            "Batman Comic",
            "Manga Volume"
        ]
    }
}

In [15]:
products = []

for i in range(1, NUM_PRODUCTS + 1):

    category = random.choice(list(product_catalog.keys()))

    subcategory = random.choice(
        list(product_catalog[category].keys())
    )

    product_name = random.choice(
        product_catalog[category][subcategory]
    )

    cost_price = round(
        random.uniform(100, 5000),
        2
    )

    products.append({
        "product_id": f"PROD{i:04d}",
        "product_name": product_name,
        "category": category,
        "subcategory": subcategory,
        "cost_price": cost_price
    })

In [16]:
indices = random.sample(range(NUM_PRODUCTS), int(NUM_PRODUCTS * 0.08))

for idx in indices:

    name = products[idx]["product_name"]

    if random.choice([True, False]):
        products[idx]["product_name"] = "  " + name + "  "
    else:
        products[idx]["product_name"] = name.swapcase()

In [ ]:
products_df = pd.DataFrame(products)

products_df.head()

  product_id  product_name  category subcategory  cost_price
0   PROD0001  Dining Table      Home   Furniture      691.21
1   PROD0002         Kurti  Clothing       Women     3740.12
2   PROD0003         Jeans  Clothing         Men     3719.16
3   PROD0004          Lamp      Home       Decor     4904.50
4   PROD0005         Dress  Clothing       Women     1868.32

In [19]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    str
 1   product_name  500 non-null    str
 2   category      500 non-null    str
 3   subcategory   500 non-null    str
 4   cost_price    500 non-null    float64
dtypes: float64(1), str(4)
memory usage: 19.7 KB

In [20]:
products_df.sample(5)

    product_id     product_name     category  subcategory  cost_price
241   PROD0242             Sofa         Home    Furniture     4946.70
34    PROD0035       Frying Pan         Home      Kitchen     3210.45
42    PROD0043           Mirror         Home        Decor     3164.50
170   PROD0171         Keyboard  Electronics  Accessories     1050.13
146   PROD0147  Data Structures        Books    Education     3730.75

In [21]:
products_df.to_csv(
    "../data/raw/products.csv",
    index=False
)

print("products.csv generated successfully!")

products.csv generated successfully!

In [22]:
orders = []

for i in range(1, NUM_ORDERS + 1):

    order_id = f"ORD{i:05d}"

    customer_id = random.choice(customers_df["customer_id"].tolist())

    region = random.choice(regions)

    status = random.choice(order_status)

    order_datetime = fake.date_time_between(
        start_date="-2y",
        end_date="now"
    )

    orders.append({
        "order_id": order_id,
        "customer_id": customer_id,
        "region": region,
        "status": status,
        "order_date": order_datetime.strftime("%Y-%m-%d %H:%M:%S")
    })

In [23]:
num_null = int(NUM_ORDERS * 0.05)

indices = random.sample(range(NUM_ORDERS), num_null)

for idx in indices:
    orders[idx]["customer_id"] = None

In [24]:
wrong_date_indices = random.sample(range(NUM_ORDERS), int(NUM_ORDERS * 0.05))

for idx in wrong_date_indices:

    dt = datetime.strptime(
        orders[idx]["order_date"],
        "%Y-%m-%d %H:%M:%S"
    )

    orders[idx]["order_date"] = dt.strftime("%d-%m-%Y %H:%M:%S")

In [25]:
orders_df = pd.DataFrame(orders)

orders_df.head()

   order_id customer_id region     status           order_date
0  ORD00001    CUST0434  South  CANCELLED  31-03-2026 18:36:11
1  ORD00002    CUST0551  South   RETURNED  2026-01-02 12:00:23
2  ORD00003    CUST0171   West  DELIVERED  2025-12-26 06:56:07
3  ORD00004    CUST0144  South  DELIVERED  2025-02-08 16:14:54
4  ORD00005    CUST0462  North  DELIVERED  2025-02-18 15:04:35

In [26]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     700 non-null    str
 1   customer_id  665 non-null    str
 2   region       700 non-null    str
 3   status       700 non-null    str
 4   order_date   700 non-null    str
dtypes: str(5)
memory usage: 27.5 KB

In [27]:
orders_df["customer_id"].isna().sum()

np.int64(35)

In [28]:
orders_df.sample(10)

     order_id customer_id region     status           order_date
270  ORD00271    CUST0177   East  CANCELLED  2024-11-28 06:23:01
417  ORD00418    CUST0228  North  DELIVERED  2025-03-02 18:56:45
440  ORD00441    CUST0556   East     PLACED  2024-11-10 18:21:45
476  ORD00477    CUST0544   West   RETURNED  2024-08-10 12:58:20
301  ORD00302    CUST0313   East  CANCELLED  2025-07-29 04:46:39
160  ORD00161    CUST0455  South     PLACED  2024-08-28 03:46:19
314  ORD00315    CUST0266   West  CANCELLED  2026-06-04 03:08:41
469  ORD00470    CUST0326  South    SHIPPED  2025-10-03 02:04:00
655  ORD00656    CUST0524   East  CANCELLED  16-06-2026 06:07:49
520  ORD00521    CUST0072  South  DELIVERED  2024-11-08 12:07:24

In [29]:
orders_df.to_csv(
    "../data/raw/orders.csv",
    index=False
)

print("orders.csv generated successfully!")

orders.csv generated successfully!

In [30]:
order_items = []

order_ids = orders_df["order_id"].tolist()
product_ids = products_df["product_id"].tolist()

# Create a lookup for product cost prices
price_lookup = products_df.set_index("product_id")["cost_price"].to_dict()

for i in range(1, NUM_ORDER_ITEMS + 1):

    order_id = random.choice(order_ids)

    product_id = random.choice(product_ids)

    quantity = random.randint(1, 5)

    cost_price = price_lookup[product_id]

    # Selling price is 20–60% above cost
    unit_price = round(cost_price * random.uniform(1.2, 1.6), 2)

    discount_percent = random.randint(0, 50)

    order_items.append({
        "order_item_id": f"ITEM{i:05d}",
        "order_id": order_id,
        "product_id": product_id,
        "quantity": quantity,
        "unit_price": unit_price,
        "discount_percent": discount_percent
    })

In [31]:
negative_indices = random.sample(
    range(NUM_ORDER_ITEMS),
    int(NUM_ORDER_ITEMS * 0.03)
)

for idx in negative_indices:

    order_items[idx]["quantity"] *= -1

In [32]:
order_items_df = pd.DataFrame(order_items)

order_items_df.head()

  order_item_id  order_id product_id  quantity  unit_price  discount_percent
0     ITEM00001  ORD00140   PROD0177         3     1165.22                 0
1     ITEM00002  ORD00504   PROD0485         4     1032.09                49
2     ITEM00003  ORD00441   PROD0409         3      795.76                50
3     ITEM00004  ORD00008   PROD0281         3     5969.29                35
4     ITEM00005  ORD00448   PROD0203         2     5560.17                47

In [33]:
order_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_item_id     2500 non-null   str
 1   order_id          2500 non-null   str
 2   product_id        2500 non-null   str
 3   quantity          2500 non-null   int64
 4   unit_price        2500 non-null   float64
 5   discount_percent  2500 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 117.3 KB

In [34]:
(order_items_df["quantity"] < 0).sum()

np.int64(75)

In [35]:
order_items_df.sample(10)

,order_item_id,order_id,product_id,quantity,unit_price,discount_percent
572,ITEM00573,ORD00125,PROD0274,-2,3164.78,24
367,ITEM00368,ORD00226,PROD0038,4,2168.65,3
1956,ITEM01957,ORD00380,PROD0075,3,4301.48,22
252,ITEM00253,ORD00574,PROD0421,3,4642.33,18
1131,ITEM01132,ORD00537,PROD0463,2,2919.98,23
450,ITEM00451,ORD00661,PROD0126,1,574.09,17
2410,ITEM02411,ORD00143,PROD0418,2,3997.26,25
989,ITEM00990,ORD00073,PROD0210,1,6248.71,7
682,ITEM00683,ORD00637,PROD0107,3,5140.96,5
509,ITEM00510,ORD00478,PROD0104,3,2809.50,31

In [36]:
order_items_df.to_csv(
    "../data/raw/order_items.csv",
    index=False
)

print("order_items.csv generated successfully!")

order_items.csv generated successfully!

In [37]:
print("Customers:", len(customers_df))
print("Products:", len(products_df))
print("Orders:", len(orders_df))
print("Order Items:", len(order_items_df))

Customers: 600
Products: 500
Orders: 700
Order Items: 2500

In [38]:
customers_df[
    ~customers_df["email"].str.contains(
        r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$',
        regex=True,
        na=False
    )
]

,customer_id,customer_name,email,registration_date,customer_type
17,CUST0018,Janani Mohanty,dalbirkhosla@,2023-11-11,REGULAR
87,CUST0088,Reyansh Mutti,wasonqasimexample.org,2024-06-12,REGULAR
95,CUST0096,Sarthak Kakar,finn23@,2025-11-15,REGULAR
246,CUST0247,Bhavna Dara,wrana@,2024-10-05,REGULAR
247,CUST0248,Bhavna Brar,riya47@,2024-05-20,REGULAR
301,CUST0302,Farhan Tella,chatresh16@,2023-11-07,REGULAR
416,CUST0417,Chatresh Chaudhuri,samesh36example.net,2025-11-18,REGULAR
458,CUST0459,Hemangini Muni,harshilrajagopal@,2026-01-11,REGULAR
487,CUST0488,Chakradev Gala,tdey@,2025-04-07,PREMIUM
500,CUST0501,Lakshmi Ram,jmunshi@,2023-08-01,REGULAR
502,CUST0503,Saumya Goel,groveroscar@,2025-09-17,REGULAR
568,CUST0569,Yuvraj Mani,rastogihema@,2025-11-19,REGULAR

In [39]:
orders_df["customer_id"].isna().sum()

np.int64(35)

In [40]:
(order_items_df["quantity"] < 0).sum()

np.int64(75)

In [41]:
orders_df[
    orders_df["order_date"].str.match(r"\d{2}-\d{2}-\d{4}")
]

     order_id customer_id region     status           order_date
0    ORD00001    CUST0434  South  CANCELLED  31-03-2026 18:36:11
10   ORD00011    CUST0579  North    SHIPPED  29-05-2025 05:24:05
91   ORD00092    CUST0245  North    SHIPPED  05-07-2025 10:53:43
138  ORD00139    CUST0335   East  CANCELLED  19-07-2024 10:46:47
159  ORD00160         NaN  North    SHIPPED  10-11-2025 01:37:35
181  ORD00182    CUST0239  South     PLACED  01-02-2026 23:56:44
232  ORD00233    CUST0305  South     PLACED  03-12-2024 14:55:30
266  ORD00267    CUST0577  North  DELIVERED  15-08-2024 12:22:57
278  ORD00279    CUST0329   East  CANCELLED  06-08-2024 05:25:47
310  ORD00311    CUST0193  South   RETURNED  18-04-2025 20:27:52
315  ORD00316    CUST0398  North   RETURNED  31-05-2025 14:14:41
317  ORD00318    CUST0228   West  DELIVERED  25-04-2025 04:15:12
355  ORD00356    CUST0376  North  CANCELLED  03-10-2025 08:14:27
374  ORD00375    CUST0093  North     PLACED  21-10-2025 11:33:18
422  ORD00423    CUST0261  South    SHIPPED  29-07-2024 08:51:29
445  ORD00446    CUST0391  South     PLACED  07-10-2025 16:29:03
452  ORD00453    CUST0399  South   RETURNED  28-09-2025 14:58:00
455  ORD00456    CUST0566  North     PLACED  25-06-2026 10:52:20
467  ORD00468    CUST0053   East  CANCELLED  30-12-2025 03:17:58
478  ORD00479    CUST0457  South   RETURNED  01-04-2026 08:53:12
487  ORD00488    CUST0216  South  CANCELLED  08-04-2025 18:12:15
493  ORD00494    CUST0572  North   RETURNED  17-05-2026 13:51:34
535  ORD00536    CUST0593   West   RETURNED  14-05-2025 19:01:03
536  ORD00537         NaN  North   RETURNED  04-11-2024 11:27:59
546  ORD00547    CUST0500  South     PLACED  01-02-2025 10:45:02
552  ORD00553    CUST0281   East   RETURNED  05-01-2026 13:33:52
553  ORD00554    CUST0558  South  CANCELLED  21-10-2024 18:41:04
561  ORD00562         NaN  South    SHIPPED  01-12-2025 03:06:26
577  ORD00578    CUST0351   West   RETURNED  02-10-2025 22:04:24
605  ORD00606    CUST0142  North    SHIPPED  09-01-2025 20:52:36
611  ORD00612    CUST0446  North     PLACED  29-01-2026 08:17:33
646  ORD00647    CUST0195   West    SHIPPED  08-11-2025 10:39:35
651  ORD00652    CUST0505  North   RETURNED  13-12-2025 13:35:43
654  ORD00655    CUST0282   West    SHIPPED  08-10-2025 08:18:54
655  ORD00656    CUST0524   East  CANCELLED  16-06-2026 06:07:49